import { ColPhoto } from './colPhoto';
import { FactFeature } from './factFeature';

export interface ColMember {
  colUserId: number;
  colUserName: string;
  firstName: string;
  lastName: string;
  colUrl: string;
  hsStudentUrl: string;
  adminUrl: string;
  hsName: string;
  hsLocation: string;
  classYear: string;
  hsGradDate: Date;
  isActive: boolean;
  gradDate: Date;
  gpa: string;
  proposedMajor: string;
  extraCurricular: string;
  dreamJob: string;
  collegeNum: number;
  collegeName: string;
  collegeNickname: string;
  collegeLocation: string;
  collegeEnrollment: string;
  tuition: number;
  roomAndBoard: number;
  averageAid: number;
  netPay: number;
  created: Date;
  lastActive: Date;
  colUserType: string;
  active: boolean;
  collegeDescription: string;
  collegeStreet: string;
  collegeCity: string;
  collegeState: string;
  collegeZip: string;
  collegePhone: string;
  collegeEmail: string;
  collegeWebsite: string;
  collegeVirtual: string;
  collegeYearFounded: string;
  collegePresident: string;
  adminContact: string;
  adminTitle: string;
  colPhotos: ColPhoto[];
  factFeatures: FactFeature[];
}
